spring:
  main:
    allow-bean-definition-overriding: true

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: username
    password: password

